[build]
target = "compiletime/x86-caelyx.json"

[target.'cfg(all())']
rustflags = ["-C", "link-arg=-Tcompiletime/linker.ld"]

[target.'cfg(target_os = "none")']
runner = "compiletime/run.sh"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]